// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "@prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  datasource: {
    // This tells Prisma CLI tools exactly where to look for your connection URL
    url: process.env.DATABASE_URL,
  },
  migrations: {
    seed: 'npx tsx ./prisma/seed.ts', 
  },
});